### PR TITLE
fixed iam role. Documentation. CDK Python upgraded to 1.78.0

### PR DESCRIPTION
**Pull request by leandrodamascena**
Fixed the IAM issue.

By default AWS creates an AWS inline policy for medialive connecting to mediapackage, I did the same.

I think now is everything ok.

### CODE REVIEW

**Comment by nideveloper** [comment]
So, I pulled this in and deployed both ts and python - no change. It still doesn't let me view the stream

**Comment by leandrodamascena** [comment]
Sorry for the trouble and spending your time, dude! But I tested it and working fine!
Can you send me some print screens? Especially about medialive channel alerts, role and iam permissions and mediapackage endpoint?
If you prefer, send me it in dm in twitter.
Thank you

**Comment by nideveloper** [comment]
alerts
network
browser

**Comment by nideveloper** [comment]
iam

**Comment by leandrodamascena** [comment]
Hmmm it looks like your images are ok. The last thing, can you check the OBS Studio configuration? I am sending the video of implantation that I made here and worked fine..

https://streamable.com/ye8bq0

Important steps
00:13 - Initial deployment
01:49-02:25 - Starting channel and OBS Configuration
03:18 - OBS Studio streaming
04:40-end - OBS Studio streaming and added/removed resources to stream (in this case I only added images in stream). Some delays happen in stream due to my internet connection.

Again, I’m sorry for your time, but I think it’s an important stack to help people who want to stream using AWS and don’t want to worry about server capacity and management, that is, 100% Serverless.

**Comment by nideveloper** [comment]
ooh I see a difference the readme says "As I said at the beginning, this Stack doesn't start your channel automatically, so go to AWS Console -> AWS Elemental MediaLive -> Inputs -> input-test1 and copy the endpoint URL. Go to OBS Studio and paste this URL (bbb is the key). " so I was taking the whole url and putting in bbb as the password (literally nothing errored) whereas you didn't take the last segment for the server and used it for the stream key. Let me try that. 

I honestly don't mind the back and forward because 99% of the patterns is making the readme bulletproof, so thanks for responding

**Comment by leandrodamascena** [comment]
Ohh sorry! I think I updated the name of the stream and forgot to update README! Nice you got it! Let me know about.

**Comment by nideveloper** [comment]
works like a dream now! awesome, I will make some readme updates and then we are good to go

**Comment by leandrodamascena** [comment]
Oh well, very nice! I couldn't update it to CDK 1.79.0 due to SPADeploy and I was afraid about some incompatibility.
But I'll open a PR in SPADeploy and when you can you update it.

The CDK team releases many versions lol

**Pull request merged**
